#!/bin/python2

alphabet = "abcdefghijklmnopqrstuvwxyz"
currentmessage = input('Enter your message: ')
newmessage = ""

def encrypt(newmessage):
  key = int(input('Enter your key:')) #store key
  for i in currentmessage:
    currentposition = alphabet.index(i) # find the position of the letter
    newposition = (currentposition + key) % 26 #gets new character position, and goes back to zero after 26
    newmessage += alphabet[newposition]
  #print'The new message is: ', newmessage
  return newmessage

def decrypt(newmessage):
  known = input('Do you have a key? (y/n): ")
  if known == y:
    key = int(input('Enter your key:')) #store key
    for i in currentmessage:
      currentposition = alphabet.index(i) # find the position of the letter
      newposition = (currentposition - key) % 26 #gets new character position, and goes back to zero after 26
      if newposition < 0:
        newposition += 26
      newmessage += alphabet[newposition]
    #print'The new message is: ', newmessage
  return newmessage

decision = input('Would you like to encrypt (e) or decrypt (d)?')
if decision == 'd':
  print 'The new message is:', decrypt(newmessage)
elif decision == 'e':
  print 'The new message is:', encrypt(newmessage)
else:
  print "Not a valid response"
